---
- name: Update existing HostFile
  hosts: localhost
  
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_ssh_port: 5986
    ansible_winrm_transport: ntlm

  pre-tasks:
    - name: read the matrix.csv
      read_csv: 
        path: /root/ansible/ansible_playbooks/matrix.csv
        key: Name
      register: matrix
      vars:
        hostAppNames: "{{ matrix.dict.hostAppNames.Value.split(',') }}" 
        sqlAddr: "{{ matrix.dict.octet1.Value }}.{{ matrix.dict.octet2.Value }}.{{ matrix.dict.octet3.Value }}.{{ matrix.dict.octet4.Value }}[3]"
   
  tasks:
    - name: Check that the hosts file exists
      win_stat:
        path: C:\Windows\System32\drivers\etc\hosts
      register: stat_result

    - name: fail if it doesnt exist already
      fail:
        msg: " hosts file does not exists "
      when: not stat_result.stat.exists
      
    - name: get contents of hosts file
      win_shell: cat C:\Windows\System32\drivers\etc\hosts
      register: hostContent
      when: stat_result.stat.exists
        
    - name: Update host file     
      block:
       - name: Add {{ sqlAddr }} as an A record for {{ item }}
         win_hosts:
           state: present
           canonical_name: {{ item }}
           ip_address: {{ sqlAddr }}
         register: updatedHosts
      when: hostContent.stdout.find('{{item}}') = -1
      loop: {{ hostAppNames }}
      
    - name: fail if hostname is already present in hosts file
      fail:
        msg: "An entry {{item}} was found with that hostname hence failing"
      when: hostContent.stdout.find('{{item}}') != -1
      loop: {{ hostAppNames }}
      