---
- hosts: all
  gather_facts: false
  tasks:
    - add_host: 
        host: "{{target_machine}}"
      when: target_machine is defined
- name: Installing the Drivers
  hosts: "{{target_machine | default('all') }}"
  gather_facts: false
  vars_files:
    - ../phase1/phase1_vault.yml
    # QLnPrintName:
    #   - printer1
    #   - printer2
    # printers:
    #   - Receipt
    #   - Slip
    #   - Endorse
  
  tasks: 
  - name: Check if the QLnDriver exists already.
    win_shell: |
       $driverexists = Get-PrinterDriver -Name {{ QLnPrintDriver }} -ErrorAction SilentlyContinue 
    register: driverexists
  
  - name: Install-QLnDriver tasks
    block:      
      - name: Check if install directory exists
        win_stat:
            path: "{{ QLnPrintDriverTargetPath }}"
        register: stat_result
             
      - name: create directory if not exists
        win_file:
          path: "{{ QLnPrintDriverTargetPath }}"
          state: directory
        when: not stat_result.stat.exists
        
      - name: Copy driver files to local drive
        win_copy:
            src: "{{ QLnPrintDriverPath }}"
            dest: "{{ QLnPrintDriverTargetPath }}"
            
      - name: Installing QLnDriver driver
        win_shell: |
            pnputil add-driver "{{ QLnPrintDriverTargetPath }}\ZBRN\ZBRN.inf" |
            Add-PrinterDriver -Name "{{ QLnPrintDriver }}" |
            Remove-Item "{{ QLnPrintDriverTargetPath }}\" -Recurse -Force
       
    when: not driverexists.changed
    delegate_to: '{{target_machine | default("all")}}'
    vars:
      ansible_connection: winrm
      ansible_winrm_server_cert_validation: ignore
      ansible_ssh_port: 5986
      ansible_winrm_transport: ntlm
      QLnPrintDriverPath: \\stp-it227\App Installs\Drivers\Printer\Zebra\QLn320\ZBRN
      QLnPrintDriver: "ZDesigner QLn320"
      QLnPrintDriverTargetPath: C:\Temp\QLN320
      file: "{{ QLnPrintDriverPath }}\PrinterDriverData.reg"