---
- hosts: all
  gather_facts: false
  tasks:
    - add_host: 
        host: "{{target_machine}}"
      when: target_machine is defined 
- name: Start services automatically
  hosts: "{{target_machine | default('all') }}"
  gather_facts: false
  vars_files:
    - ../phase1/phase1_vault.yml
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_ssh_port: 5986
    ansible_winrm_transport: ntlm
    services:
      - NetTcpPortSharing
      - NetTcpActivator
      - NetPipeActivator
        
  tasks:
    - block:
      - name: set service name
        win_service:
          name: "{{ item }}"
          start_mode: auto
          state: started
        loop: "{{ services }}"
      - name: restart the service
        win_service:
          name: "{{ item }}"
          force_dependent_services: yes
          state: restarted
        loop: "{{ services }}"