---
- hosts: all
  gather_facts: false
  tasks:
    - add_host: 
        host: '{{target_machine}}'
      when: target_machine is defined  
#This Play is used to create Virtual Switch
- name: Creating Virtual switch
  hosts: '{{target_machine | default("all")}}'
  vars_files:
    - phase1_vault.yml
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_ssh_port: 5986
    ansible_winrm_transport: ntlm
  tasks:
  - name: Creating dummy switch
    win_shell: |
      if (!(Get-VMSwitch -Name STP -ErrorAction Silently Continue)) {
          New-VMSwitch -Name STP -SwitchType Internal
      } else {
          if ((Get-VMSwitch -Name STP).SwitchType -ne "Internal") {
              Get-VMSwitch -Name STP | Set-Switch -SwitchType "Internal"
          }
      }
    register: vswitch_out
  - debug:
      msg: '{{ vswitch_out.stdout_lines }}'
