---
- hosts: all
  gather_facts: false
  tasks:
    - add_host: 
        host: '{{target_machine}}'
      when: target_machine is defined
- name: Exporting images on Gold Hyper-v
  hosts: '{{target_machine | default("all")}}'
 
  vars:
    ansible_winrm_server_cert_validation: ignore
    ansible_ssh_port: 5986
    ansible_winrm_transport: ntlm
    ansible_connection: winrm
  tasks:
   - name: Clearing the existing Export folder
     win_file:
       path: F:/Export
       state: absent
   - name: Export VM's from Gold Hyper-V
     win_shell: |
      Export-VM -Name "{{ item }}"  -Path F:\Export
     loop:
     - stp-000stgadc1
     - stp-000stgapp1
     - STP-WHALLEYSQL1