---
- hosts: all
  gather_facts: false
  tasks:
    - add_host: 
        host: '{{target_machine}}'
      when: target_machine is defined  
# This play is performed to validate and run initial configuration of the Hyperv
- name: validate and configure the hyperv
  hosts: '{{target_machine | default("all")}}'
  vars_files:
    - config_vault.yml
  vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_ssh_port: 5986
  tasks:
   
   - name: check ifwinrm is up
     wait_for:
       port: 5986
       timeout: 10
       host: '{{target_machine}}'
     register: winrm_available
     ignore_unreachable: yes
     ignore_errors: yes
   - name: check if powershell version is 5 
     win_shell: |
        [string]$PSVersionTable.PSVersion.Major + "." + [string]$PSVersionTable.PSVersion.Minor
     register: powershell_version
     failed_when:
     - powershell_version.stdout_lines[0] != "5.1"
   - name: Join computer to domain
     win_domain_membership:
       dns_domain_name: stp.local
       hostname: '{{hostname}}'
       domain_admin_user: '{{admin_user}}'
       domain_admin_password: '{{admin_pass}}'
       domain_ou_path: "OU=Retail Virtual Hosts,OU=Retail,OU=Servers,DC=STP,DC=LOCAL"
       state: domain
     register: domain_state
   - win_reboot:
     when: domain_state.reboot_required
