---
- hosts: all
  gather_facts: false
  tasks:
    - add_host: 
        host: '{{target_machine}}'
      when: target_machine is defined  
- name: Importing VM's
  hosts: '{{target_machine | default("all")}}'
  gather_facts: false
  vars_files:
    - phase1_vault.yml
  tasks:
    - name: read the matrix.csv
      read_csv: 
        path: /root/ansible/ansible_playbooks/phase1/matrix.csv
        key: Name
      register: matrix
      delegate_to: localhost
    - name: Importing VM's
      block:
        - name: looping through the VM files for import
          win_find:
            paths: F:\Export\{{item}}\Virtual Machines
            patterns: ['*.vmcx'] 
          register: vmfile
          loop:
            - stp-000stgadc1
            - stp-000stgapp1
            - STP-WHALLEYSQL1
        - name: loop through the items matched
          win_shell: |
            $vhdpath = '{{matrix.dict.importPath.Value}}' + '\Virtual Hard Disks'
            $vmpath = '{{matrix.dict.importPath.Value}}' + '\Virtual Machines'
            $snappath = '{{matrix.dict.importPath.Value}}' + '\Snapshots'
            Import-VM -Path '{{item.files[0].path}}' -GenerateNewId -Copy -VhdDestinationPath $vhdpath -VirtualMachinePath $vmpath -SnapshotFilePath $snappath -SmartPagingFilePath $vmpath
          loop: "{{ vmfile.results|flatten(levels=1) }}"
      delegate_to: '{{target_machine | default("all")}}'
      vars:
        ansible_winrm_server_cert_validation: ignore
        ansible_ssh_port: 5986
        ansible_winrm_transport: ntlm
        ansible_connection: winrm