---
- hosts: all
  gather_facts: false
  tasks:
    - add_host: 
        host: '{{target_machine}}'
      when: target_machine is defined 
- name: creating production virtual switch
  hosts: '{{target_machine | default("all")}}'
  gather_facts: false
  vars_files:
    - phase1_vault.yml
  tasks:
    - name: read the matrix.csv
      read_csv: 
        path: /root/ansible/ansible_playbooks/phase1/matrix.csv
        key: Name
      register: matrix
      delegate_to: localhost
    - name: creating a prod switch
      block:
        - name: set required variables
          win_shell: |
              $newvnet = "{{matrix.dict.newVnet.Value }}"
              $netadapter = "{{ matrix.dict.IPnetadapter.Value }}"
              $VMAdapter = Get-NetAdapter -Name $netadapter -EA SilentlyContinue
              if (!$VMAdapter) {
                $VMAdapter = Get-NetAdapter | Where-Object {($_.Status -eq "Up") -and ($_.Name -ne "Embedded LOM 1 Port 1")} | Select-Object -First 1 }
            
        - name: create switch 
          win_shell: |
              $newvnet = "{{ matrix.dict.newVnet.Value }}"
              $VMAdapter = Get-NetAdapter -Name "{{ matrix.dict.IPnetadapter.Value }}" -EA SilentlyContinue
              echo " value of newvnet: $newvnet | value of VMAdapter: $VMAdapter "  
              New-VMSwitch -Name $newvnet -NetAdapterName $VMAdapter.Name -AllowManagementOS $False -ErrorAction Stop
          register: vswitch_new
      
          
        - name: debug output of create switch task
          debug: 
           msg: "{{ vswitch_new }}"

        - name: virtual switch was not created successfully
          debug:
            msg: "The virtual switch was not created successfully. Please check configuration and try again."
          when: vswitch_new == false
      delegate_to: '{{target_machine | default("all")}}'
      vars:
        ansible_connection: winrm
        ansible_winrm_server_cert_validation: ignore
        ansible_ssh_port: 5986
        ansible_winrm_transport: ntlm 

