---
# performing server hardening
- hosts: all
  gather_facts: false
  tasks:
    - add_host: 
        host: '{{target_machine}}'
      when: target_machine is defined

- name: refresh virtual machines
  hosts: '{{target_machine | default("all")}}'
  gather_facts: true
  vars:
    ansible_winrm_server_cert_validation: ignore
    ansible_ssh_port: 5986
    ansible_winrm_transport: ntlm
    ansible_connection: winrm
  
  tasks:
     - name: copy secure configuration script
       win_copy:
         src: ./Set-VMSecureConfiguration.ps1
         dest: C:\Temp\Set-VMSecureConfiguration.ps1
         remote_src: yes
       register: copy_script

     - name: debug copy task
       debug:    
         msg: "{{ copy_script }}"

     - name: execute secure configuration script
       win_command: powershell.exe -ExecutionPolicy ByPass -File "C:\Temp\Set-VMSecureConfiguration.ps1"
       register: output_wincmd
       
     - name: debug execute task
       debug:    
         msg: "{{ output_wincmd }}"