---
- hosts: all
  gather_facts: false
  tasks:
    - add_host: 
        host: '{{target_machine}}'
      when: target_machine is defined  
#SNMP Configuration
- name: SNMP Configuration
  hosts: localhost
  tasks:
     - name: read the matrix.csv
       read_csv: 
         path: /root/ansible/ansible_playbooks/phase1/matrix.csv
         key: Name
       register: matrix 
     - name: configuring the SNMP process
       block:
         - name: Check install status
           win_shell:   |
               $install = Get-WindowsFeature -Name SNMP-Service
               $install | ForEach-Object {
                   $status = $install.Installed
                   $status
               }
               
               # Install feature
               if (!($status -eq $true)) {
                   Write-Output "SNMP service is not installed. Installing."
                   $null = Install-WindowsFeature -Name SNMP-Service -IncludeAllSubFeature -IncludeManagementTools
               } else {
                   Write-Output "SNMP service is already installed."
               }
           ignore_errors: yes
           register: check_status
           
         - name: Configure SNMP
           win_shell:   |
               $hvIP = "{{matrix.dict.octet1.Value }}" + "." + "{{matrix.dict.octet2.Value }}" + "." + "{{matrix.dict.octet3.Value }}" + "." + "5"
               $managers = '10.1.1.18', $hvIP
               $i = 2
               foreach ($manager in $managers) {
                   New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\services\SNMP\Parameters\PermittedManagers"  -Name $i -Value $manager
                   $i++
               }
           ignore_errors: yes
           register: config_status
           
           
         - name: Add community strings. Can add more here if needed
           win_shell:   |
               $strings = @(
                     @{
                         Name = "2v2l2nch3"
                         Rights = 8    # 4 is read-only, 8 is read write.
                     }
                 )
                 
                 foreach ($string in $strings) {
                     New-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\services\SNMP\Parameters\ValidCommunities"  -Name $string.Name -Value $string.Rights
                     $i++
                 }
           register: add_community  
       
       delegate_to: '{{target_machine}}'
       vars:
         ansible_connection: winrm
         ansible_winrm_server_cert_validation: ignore
         ansible_ssh_port: 5986
         ansible_winrm_transport: ntlm  