---
# This playbook would get the list of virtual machines from hypervisor then rename and reboot
- hosts: all
  gather_facts: false
  tasks:
    - add_host: 
        host: '{{target_machine}}'
      when: target_machine is defined

- name: refresh virtual machines
  hosts: '{{target_machine | default("all")}}'
  gather_facts: true
  vars_files:
    - phase1_vault.yml
  vars:
    ansible_winrm_server_cert_validation: ignore
    ansible_ssh_port: 5986
    ansible_winrm_transport: ntlm
    ansible_connection: winrm
    store_number: "{{store_number}}"
    
  tasks:
     - name: get the list of virtual machines on hypervisor
       win_command: powershell Get-VM -ComputerName {{ hyper_v_name }} #| Where-Object {$_.State -eq 'Running'}
       register: vmlist
       
     - name: list servers on hyper-v
       debug:
         msg: "{{ vmlist.stdout_lines }}"
               
     - name: set configurations for app server
       win_shell: |
        Set-VM -VMName 'stp-000stgapp1' -MemoryMaximumBytes 16384MB
        Set-VMProcessor -VMName 'stp-000stgapp1' -Count 16
        Get-VM -VMname 'stp-000stgapp1' | Set-VM -AutomaticStartAction Start -AutomaticStartDelay 180
        Disconnect-VMNetworkAdapter -VMName 'stp-000stgapp1'
        Enable-VMIntegrationService -VMName 'stp-000stgapp1' -Name *
        Rename-VM -VMName 'stp-000stgapp1' -NewName "{{ 'stp-000stgapp1' | replace('000stg', store_number) }}"
          Start-VM -Name 'stp-{{store_number}}app1'
       when: item.find('app') != -1
       with_items: "{{ vmlist.stdout_lines }}"
       
     - name: set configurations for adc server
       win_shell: |
        Set-VM -VMName 'stp-000stgadc1' -MemoryMaximumBytes 16384MB
        Set-VMProcessor -VMName 'stp-000stgapp1' -Count 4
        Get-VM -VMname 'stp-000stgadc1' | Set-VM -AutomaticStartAction Start -AutomaticStartDelay 60
        Disconnect-VMNetworkAdapter -VMName 'stp-000stgadc1'
        Enable-VMIntegrationService -VMName 'stp-000stgadc1' -Name *
        Rename-VM -VMName 'stp-000stgadc1' -NewName "{{ 'stp-000stgadc1' | replace('000stg', store_number) }}"
          Start-VM -Name 'stp-{{store_number}}adc1'
       when: item.find('adc') != -1
       with_items: "{{ vmlist.stdout_lines }}"
       
     - name: set configurations for sql server
       win_shell: |
        Set-VM -VMName 'STP-WHALLEYSQL1' -MemoryMaximumBytes 65536MB
        Set-VMProcessor -VMName 'STP-WHALLEYSQL1' -Count 4
        Get-VM -VMname 'STP-WHALLEYSQL1' | Set-VM -AutomaticStartAction Start -AutomaticStartDelay 120
        Disconnect-VMNetworkAdapter -VMName 'STP-WHALLEYSQL1'
        Enable-VMIntegrationService -VMName 'STP-WHALLEYSQL1' -Name *
        Rename-VM -VMName 'STP-WHALLEYSQL1' -NewName "{{ 'stp-000sql1' | replace('000', store_number) }}"
        Start-VM -Name 'stp-{{store_number}}sql1'
        
       when: item.find('SQL') != -1
       with_items: "{{ vmlist.stdout_lines }}"