---
- name: Configure New App
  hosts: localhost
  
  tasks: 
    - name: OMS Deployment
      block:
        - name: copying OMS 
          win_copy:
            src: \\stp-it225\STPDeployments\Oms\Production\DeploymentScripts\InstallScripts\CopyOmsRetailServerDeployments.bat
            dest: C:\OmsUtilities\InstallScripts
            force: yes
          register: cpyOmsRetailServerDeployments
          
        - name: Install Copy Oms Retail Server Deployments
          win_package:
            path: C:\OmsUtilities\InstallScripts\CopyOmsRetailServerDeployments.bat
            arguments: /package
            state: present
                   
        - name: Install Oms Retail Server Deployments
          win_package:
            path: C:\OmsUtilities\InstallScripts\OmsRetailServerDeployments.bat
            arguments: /package
            state: present
                    
        - name: get OMS version
          win_shell: 'type \\stp-retapp151\C`$\OMS\Oms.RetailWebService\Ver.txt'  
          register: OMSVersion
         
        - name: Install OMS Copy service
          win_package:
            path: C:\OMS\InstallRetailServerCopyOnly.bat {{ OMSVersion.stdout_lines }}
            arguments: /c
            state: present
          when: OMSVersion.stdout_lines is defined
          register: instOMSCpy
          
        - name: Install OMS service
          win_package:
            path: C:\OMS\InstallRetailServerInstallOnly.bat {{ OMSVersion.stdout_lines }}
            arguments: /c
            state: present
          when: OMSVersion.stdout_lines is defined
          register: instOMS
          
        - name: Prepare PromoService
          win_package:
            path: C:\OMSUtilities\PromoServiceDeploymentScripts\PreparePromoService_Retail.bat
            arguments: /c
            state: present
          register: PrepPromoServ
          
        - name: Installing Promo Service
          win_package:
            path: C:\OMSUtilities\PromoServiceDeploymentScripts\FinalizePromoService.bat
            arguments: /c
            state: present
                    
        - name: Installing RetailFrameworkPrepare Service
          win_package:
            path: C:\OmsUtilities\InstallScripts\RetailFrameworkPrepare.bat {{ OMSVersion.stdout_lines }}
            arguments: /c
            state: present
          when: OMSVersion.stdout_lines is defined
          
        - name: Installing RetailFrameworkFinalize Service
          win_package:
            path: C:\OmsUtilities\InstallScripts\RetailFrameworkFinalize.bat {{ OMSVersion.stdout_lines }}
            arguments: /c
            state: present
          when: OMSVersion.stdout_lines is defined
          
        - name: Install Deployment Agent
          win_package:
            path: C:\Temp\StpDeploymentAgent.msi
            arguments: /package
            state: present
      become: True
      become_method: runas
      become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      deligate_to: 10.1.74.61