---
 - name: creating production virtual switch
   hosts:	all
   vars:
    ansible_connection: winrm
    ansible_winrm_server_cert_validation: ignore
    ansible_ssh_port: 5986
    ansible_winrm_transport: ntlm
  
   pre_tasks:
    - name: read the matrix.csv
      read_csv: 
        path: /root/ansible/ansible_playbooks/matrix.csv
        key: Name
      register: matrix

   tasks:
    - name: set required variables
      win_shell: |
        $newvnet = "{{ matrix.dict.newVnet.Value }}"
        $netadapter = "{{ matrix.dict.IPnetadapter.Value }}"
        $force = "{{ matrix.dict.VnetForce.Value }}"
        $VMAdapter=Get-NetAdapter -Name $netadapter -EA SilentlyContinue
        if (!$VMAdapter) {
            $VMAdapter=Get-NetAdapter | Where-Object {($_.Status -eq "Up") -and ($_.Name -ne "Embedded LOM 1 Port 1")} | Select-Object -First 1 }
        
    - name: create switch 
      win_command: New-VMSwitch -Name $newvnet -NetAdapterName $VMAdapter.Name -AllowManagementOS $force -ErrorAction Stop
      register: vswitch_new
      ignore_errors: yes
      
    - debug: 
       msg: "{{ vswitch_new }}"

    - name: already bound
      debug:
       msg: "The network adapter is already being used as a virtual adapter. Specify another adapter of romove the existing network."
      when: "'already bound' in vswitch_new.msg"
      register: vswitch_already_bound

    - name: virtual switch was not created successfully
      debug:
       msg: "The virtual switch was not created successfully. Please check configuration and try again."
      when: vswitch_new == false 
