---
 - name: Install Splunk agent on VM.
   hosts: 10.1.74.53
   gather_facts: true
   vars_files:
     - matrix.yml 
   
   tasks:
     - name: Install Splunk agent on VM.
       win_shell:   |
           $temp = "{{ temp }}\Splunk"
           $installer = "{{ splunkInstall }}\STPStoreDeviceConfig"
           $splunk_home = "{{ splunkHome }}"
           $controller = "{{ octet1 }}.{{ octet2 }}.{{ octet3 }}.{{ octet4 }}5"
           $path = "{{ hostFile }}"
           Write-Output "Beginning install attempt on $($ENV:computername)."
           Write-Host "Checking Splunk install status."
           $software = Get-ItemProperty "HKLM:\Software\Microsoft\Windows\CurrentVersion\Uninstall\*"
           $software += Get-ItemProperty "HKLM:\Software\Wow6432Node\Microsoft\Windows\CurrentVersion\Uninstall\*"
           $installed = $software | Where-Object {$_.DisplayName -eq "UniversalForwarder"}
           If (!($installed)) {
             Write-Output "Splunk is not installed. Beginning install process."
             
             if (!(Test-Path $temp)) {
                 Write-Host "Creating temp directory."
                 $null = New-Item -ItemType Directory -Path $temp -Force
             }
             
             Write-Output "Copying installer files to local directory."
             Copy-Item "$installer\*" $temp -Recurse -Force
             
             #Modify host file.
             $test = (Get-ChildItem -Path $path | Select-String -Pattern "controller")
             
             if (!$test) {
                 Add-Content -Path $path -Value "# Splunk forwarder"
                 Add-Content -Path $path -Value "$controller controller"
                 Write-Host "Host file entry for controller ($controller) has been added."
             }
             
             Write-Output "Starting install process at $(Get-Date)"
             Start-Process msiexec.exe -ArgumentList "/i $temp\latest.msi AGREETOLICENSE=yes LAUNCHSPLUNK=0 GENRANDOMPASSWORD=1 /quiet /L*v $temp\splunk_install.log" -Wait
             Write-Host "Installer finished running at $(Get-Date)"
             
             #Script for modifying inputs and server.conf
             
             $inputs = $splunk_home + '\etc\system\local\inputs.conf'
             $server = $splunk_home + '\etc\system\local\server.conf'
             
             $serviceName = 'SplunkForwarder'
             
             # Stop service if running
             $arrService = Get-Service -Name $serviceName
             
             while ($arrService.Status -eq 'Running') {
                 Write-Host "Stopping service $serviceName"
                 Stop-Service $serviceName
                 Start-Sleep -seconds 30
                 $arrService.Refresh()
             }
             
             Write-Host "$serviceName service is now stopped."
             
             # Delete existing .conf files
             Write-Host "Removing old configuration files."
             if (Test-Path $inputs) {
                 Remove-Item ($inputs)
             }
             
             if (Test-Path $server) {
                 Remove-Item $server
             }
             
             # FQDN
             $hostname = [System.Net.DNS]::GetHostByName('').HostName.ToLower()
             
             Write-Host "Writing configuration files."
             "[default]`r`nhost = $($hostname)" | Out-File $inputs
             "[general]`r`nserverName = $($hostname)" | Out-File $server
             
             
             #Remove splunk.log in TEMP Dir
             Write-Host "Removing temporary logs."
             Remove-Item "$Env:TEMP\..\splunk.log" -Force -ErrorAction Ignore
             Remove-Item "$Env:TEMP\splunk.log" -Force -ErrorAction Ignore
             
             
             #Move Required folders to apps folder
             Write-Host "Copying custom files and folders."
             Move-Item -Path "$temp\900_if_gateway_stpstores" -Destination "$splunk_home\etc\apps\"
             Move-Item -Path "$temp\mgmt-rest-disable_uh" -Destination "$splunk_home\etc\apps\"
             Move-Item -Path "$temp\win_siem_uh" -Destination "$splunk_home\etc\apps\"
             
             Move-Item -Path "$temp\win_splunk-btool-internal-logs_uh" -Destination "$splunk_home\etc\apps\"
             Move-Item -Path "$temp\win_splunk-purge_uf" -Destination "$splunk_home\etc\apps\"
             Move-Item -Path "$temp\win_perfmon-disk_uh" -Destination "$splunk_home\etc\apps\"
             Move-Item -Path "$temp\config_version_2020-02-18" -Destination "$splunk_home\etc\apps\"
             
             Write-Output "Starting Splunk."
             & "$splunk_home\bin\splunk.exe" start
             
             # Delete temporary files
             Write-Host "Cleaning up."
             Remove-Item $temp -Recurse -Force
             
             Write-Output "Install process completed."
           }Else {
               Write-Output "Looks like Splunk UF version $($installed.DisplayVersion) is already installed at $splunk_home"
               Write-Output "Please uninstall existing version before attempting to update."
           }
       ignore_errors: yes
       register: install_splunk
        
     - name: debug install splunk agent
       debug:
         msg: "{{ install_splunk }}"