---
# This playbook would perform server hardning process

 - name: perform server hardening process
   hosts: 10.1.74.53
   gather_facts: true
   vars:
     - ansible_connection: winrm
     - ansible_winrm_server_cert_validation: ignore
     - ansible_ssh_port: 5986
     - ansible_winrm_transport: ntlm 

   tasks:
    - name: Install 7zip from a network share with specific credentials
      win_package:
        path: \\stp-it227\App Installs\Crowdstrike\WindowsSensor.exe
        product_id: '{FAA122281AE74AC99A41598A35C684B2-18}'
        arguments: /install /quiet /norestart
        state: present
      become: yes
      become_method: runas
      become_flags: logon_type=new_credentials logon_flags=netcredentials_only
      vars:
        ansible_become_user: stp\anv00011STP
        ansible_become_password: Welcome1234!
      register: WindowsSensor
    - debug: 
        msg: "{{ WindowsSensor }}"
       
    
